### ISSUE TITLE
Pretrained Weights for Inference Only

### ISSUE THREAD

**Issue by Optimox** [rezazad68/BCDU-Net#13]
Hello, thanks for this nice repo.

I was wondering, can I access a pretrained model just to make inference on new images?

From reading the README it seems that I'll need to run the training pipeline first before being able to infer on new images.

I think it would be useful for a lot of people to directly access pretrained weights, would you consider sharing them?

Thanks!

**Comment by rezazad68** [comment]
The pre-trained weights are already in the main page! 

at the end of page
https://github.com/rezazad68/BCDU-Net

**Comment by Optimox** [comment]
Sorry I missed that! Thank you!
