### ISSUE TITLE
Test your model on PNG retina images

### ISSUE THREAD

**Issue by mjbeyeler** [rezazad68/BCDU-Net#14]
Hi

I would like to run your pre-trained model on some retina images from a different dataset.

Your evaluate model seems to be dependent on some hdf5 structure. Is there a simple method you could propose to make segmentation prediction possible from some .png images?

Michael

**Comment by rezazad68** [comment]
Hi, you need to write a similar code using open cv for reading your png images. It is just a data preparation process that you need to do for your own dataset. Best
