### ISSUE TITLE
TypeError: ('Keyword argument not understood:', 'input')

### ISSUE THREAD

**Issue by AsifAhmadKhan** [rezazad68/BCDU-Net#16]
Hello, sir! I hope you are doing well.
While training the model for the skin data set i came across this error:

_TypeError: ('Keyword argument not understood:', 'input')_ 

I am training on google colab; the error refers to:
![error pic](https://user-images.githubusercontent.com/54246513/90372434-d9f3db00-e089-11ea-8e4a-64150999555b.PNG)

Your help in this regard would be highly appreciated.
Looking forward for your kind response,
Asif Ahmad

**Comment by AsifAhmadKhan** [comment]
> Hello, sir! I hope you are doing well.
> While training the model for the skin data set i came across this error:
> 
> _TypeError: ('Keyword argument not understood:', 'input')_
> 
> I am training on google colab; the error refers to:
> ![error pic](https://user-images.githubusercontent.com/54246513/90372434-d9f3db00-e089-11ea-8e4a-64150999555b.PNG)
> 
> Your help in this regard would be highly appreciated.
> Looking forward for your kind response,
> Asif Ahmad

Just replaced 

_model = Model(input = inputs, output = conv9)_

by 

_model = Model(inputs = inputs, outputs = conv9)_

The error is gone now.
I think it was due to new version of tensorflow.

**Comment by AsifAhmadKhan** [comment]
Now closing the issue.
Thank you so much for the work, sir!

**Comment by nakulp21** [comment]
Hi, @AsifAhmadKhan, I'm also facing the same issue, but even after applying the your solution, I'm getting the same error.

**Comment by nakulp21** [comment]
> Hi, @AsifAhmadKhan, I'm also facing the same issue, but even after applying the your solution, I'm getting the same error.

Hey, I changed the code in the following manner and it worked for me.
I changed
`model = Model(input = inputs, output=conv9`

to 

`model = Model(inputs, conv9)`
