### ISSUE TITLE
OSError: Unable to open file (file read failed: time = Thu Aug 20 18:35:54 2020 ...

### ISSUE THREAD

**Issue by AsifAhmadKhan** [rezazad68/BCDU-Net#18]
Hello, sir!
I trained the model for the skin images, everything went smooth and well. In the **evaluate.py** this error occured:

![error1](https://user-images.githubusercontent.com/54246513/90811969-f4a2aa00-e33e-11ea-9db3-64b9470c2d16.PNG)

![error2](https://user-images.githubusercontent.com/54246513/90812001-02582f80-e33f-11ea-96a3-feb1d13629bc.PNG)

I am training the model on Google Colab. Kindly look into it. I am looking forward for your response. Thanks a lot!
Asif Ahmad

**Comment by AsifAhmadKhan** [comment]
Instead of
 `model.load_weights('weight_isic18')` 

I used
 
`path = 'weight_isic18'`
`from keras.models import load_model`
`model = load_model(path)`

The error gone then.
I am not sure if it is correct or not.
Kindly sir have look at this.

I got:

![ROC](https://user-images.githubusercontent.com/54246513/91033794-64ee4b80-e61d-11ea-8422-1e1d31e69bcf.png)

![Precision_recall](https://user-images.githubusercontent.com/54246513/91033883-87806480-e61d-11ea-85ec-5e37b4d38014.png)


and sample_results as a blank white page. I do not know why? Kindly help here, sir.

And also got figures of ten results as blank:

![download](https://user-images.githubusercontent.com/54246513/91034145-ecd45580-e61d-11ea-9ee2-c1a619e20c89.png)


While, **Jaccard similarity score: 0.9308885721059946**

**F1 score (F-measure): 0.8299997148892417**

**Comment by ISIC-CVPR20** [comment]
It seems that model trained but not sure trained well or not. You can also use the pre-trained weight that I uploaded in the main page. Since your are using the Colab you need to revise the image saving path to the google drive. The above diagrams does not contain any images, they are empty

**Comment by AsifAhmadKhan** [comment]
> It seems that model trained but not sure trained well or not. You can also use the pre-trained weight that uploaded in the main page. Since your are using the Colab you need to revise the image saving path to the google drive. The above diagrams does not contain any images, they are empty

Thank you dear for the response. I am confused if the model is not trained well then why I have got the ROC and Precision- recall Curve identical to the mentioned in the paper; and have also got JS and F1-score very much close to the same obtained by the authors.

**Comment by rezazad68** [comment]
Dear thanks for your interest in our work. As I can see from your results, the model trained well and the only problem is related to showing the result. It may cause because of the Colab as it needs to save and load from google drive, make sure you modify the related part of the code. The above picture does not show any picture because those figures seem empty. 

Best

**Comment by AsifAhmadKhan** [comment]
> Dear thanks for your interest in our work. As I can see from your results, the model trained well and the only problem is related to showing the result. It may cause because of the Colab as it needs to save and load from google drive, make sure you modify the related part of the code. The above picture does not show any picture because those figures seem empty.
> 
> I tried many times but all my efforts went in vain. Could you please help me, would be very thankful. If time allows you.

**Comment by AsifAhmadKhan** [comment]
> Dear thanks for your interest in our work. As I can see from your results, the model trained well and the only problem is related to showing the result. It may cause because of the Colab as it needs to save and load from google drive, make sure you modify the related part of the code. The above picture does not show any picture because those figures seem empty.
> 
> Best

 I tried many times but all my efforts went in vain. Could you please help me, would be very thankful. If time allows you.
