### ISSUE TITLE
Multimodality input: T1, T2, etc.

### ISSUE THREAD

**Issue by PinchukTS** [rezazad68/BCDU-Net#20]
Good day to you. Is it possible to pass more than single channel (grayscale) arrays to model. I would like to train on my own dataset with MRI images: T1-wrighted, T2-weighted, T2 TIRM, DWI, SWI. All of images have same shape (512, 512, 1) and want to encode them as (512, 512, 5) input.
Should I modify model exept `input_size=(512, 512, 5)` param of `BCDU_net_D3` function?

P.S. Sorry for my english :(.

**Comment by rezazad68** [comment]
Thanks for your interest. Yes, you can use any input shape for example (H, W, C) where C can be 1 channel (like Retina), 3 channels like Sking,  to N channels(for your case 5 channels). Just make sure the model you are using does not load the pre-trained weights with 3 channels as input. Best.
