### ISSUE TITLE
No license, no copyright notice is included in the project

### ISSUE THREAD

**Issue by sdinot** [rezazad68/BCDU-Net#21]
Dear Reza,

We would like to use some of your project's features in an application we plan to release under the permissive open source Apache v2.0 license, but I found no copyright or license notice in the project repository. Can you clarify this information and make it appear in your source code? Without it, it is impossible to legally use your source code, because copyright law strictly applies and prohibits any reuse.

If you don't have any idea about this, you'll find detailed information in the *Github documentation* and on the *Open Source Guides*:
* [Licensing a repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#where-does-the-license-live-on-my-repository)
* [The Legal Side of Open Source](https://opensource.guide/legal/)

Thank you very much for your work and thank you in advance for your clarifications.

Sébastien

**Comment by rezazad68** [comment]
Thanks for your interest. I have added the MIT license, so permission is hereby granted and free of charge. hope it works well for you.

Best

**Comment by sdinot** [comment]
Thank you very much.

To make legal status clearer for everyone, I propose to you an enhancement of the README file via the pull request #22.
