### ISSUE TITLE
evaluate problem

### ISSUE THREAD

**Issue by ljc1231** [rezazad68/BCDU-Net#25]
i first run the skin lesion project and succeed
then i try to change my own dataset, it is .nii format, and i train model have the following picture
![11](https://user-images.githubusercontent.com/67781186/99186109-ed960700-2788-11eb-8847-06abc7b295a8.png)
but when i evaluate a nii(and it is in my validation), but it evaluate the same value at every pixel, i have no idea how to fix it
![222](https://user-images.githubusercontent.com/67781186/99186142-3ea5fb00-2789-11eb-885b-cd417b4fe1b3.png)
can you help me please, thx!

**Comment by rezazad68** [comment]
Hi

Thanks for your interest. Considering the validation accuracy, It seems to me that your object of interest is so small, is that correct? If it is highly imbalanced you need to use patch-wise learning (check the retina one). 
Check the probability of pixel belongs to the foreground and background on your train sample by simply counting the foreground and background on your sample and dividing by the total pixels. What is the average for the whole train set for each class? This way you can see if the foreground probability is so low (like  0.03 ) then you need to use patch-wise for better performance.

Best

**Comment by ljc1231** [comment]
> Hi
> 
> Thanks for your interest. Considering the validation accuracy, It seems to me that your object of interest is so small, is that correct? If it is highly imbalanced you need to use patch-wise learning (check the retina one).
> Check the probability of pixel belongs to the foreground and background on your train sample by simply counting the foreground and background on your sample and dividing by the total pixels. What is the average for the whole train set for each class? This way you can see if the foreground probability is so low (like 0.03 ) then you need to use patch-wise for better performance.
> 
> Best

yes, i check the probability , most are less then 0.03.   patch-wise means i have to segment the ct into small pieces? like 64*64?
and i need to make sure every pieces to include part of lesion? i just slicer the 3d ct into 2d slicer without other augmentation, i will try if it could train better after regular augmentaion, thx!
