### ISSUE TITLE
There is a big gap, compared with the model you provided

### ISSUE THREAD

**Issue by 675492062** [rezazad68/BCDU-Net#30]
Maybe it's the problem of experimental setup. My experimental results are worse than those provided in the paper. Is there any extra tricks to follow?

**Comment by rezazad68** [comment]
Thanks for your feedback. I am not sure which dataset or setting you are following but the paper results are fine and easily reproducible. Please follow the code and instructions carefully. Best

**Comment by 675492062** [comment]
Thank you for your reply. Following your code, the results reported in paper are really easy to get, it may be the problem of data processing before.

**Comment by rezazad68** [comment]
Thanks for your feedback and happy that you solved the problem.

**Comment by saikrishnavanaparthi99** [comment]
> Thank you for your reply. Following your code, the results reported in paper are really easy to get, it may be the problem of data processing before.
> 
> 

Sir please guide me in training the model on skin lesion images as I am getting worst results.
