### ISSUE TITLE
performance evaluation

### ISSUE THREAD

**Issue by 675492062** [rezazad68/BCDU-Net#32]
In file "evaluate_performance.py ", you flatten all tesing data to an array, and fed it into jaccard_similarity_score,f1_score and so on. However, the general practice is to evaluate each input data and then average them. The results of the two methods are quite different, although the accuracy is the same.

**Comment by 675492062** [comment]
I think these two evaluation schemes should be feasible and scientific. Is it difficult to draw the ROC curve if you do a single image test? Am I right? Thank you!

**Comment by rezazad68** [comment]
Thanks for your feedback. For performance evaluation, we followed the related work.
