### ISSUE TITLE
Multiple issue while running the code 

### ISSUE THREAD

**Issue by Dhyani01** [rezazad68/BCDU-Net#35]
1: Skin Lesion dataset download link is not active.
2: In prepare_dataset_DRIVE.py of retina blood vessel segmentation folder this script is not running properly.

**Comment by mmheydari97** [comment]
I believe using go_backwards=True does not make a ConvLSTM bidirectional. It just makes the input reversed. Instead there should be a Bidirectional layer wrapping around the ConvLSTM to do the job. This way there would be two outputs for forward and backward cells. I'm not sure if those should be concatenated or averaged based on the model proposed.

**Comment by GauravRohilla605** [comment]
which version of tensorflow is used in development
