### ISSUE TITLE
Scoring Run time too high

### ISSUE THREAD

**Issue by GauravRohilla605** [rezazad68/BCDU-Net#36]
It tried implementing this repo.
For scoring the test dataset, it is taking around 90 mins.

Attached is the screenshot.

Can you please help in order to identify the issue ?

Regards,
Gaurav

**Comment by rezazad68** [comment]
Dear @GauravRohilla605 Thanks for your interest in our work. I can't find your attachment. Could you please specify which dataset you are using? if you are using your own dataset you can also clarify which of our method you are utilizing (patch-wise or image sample)? 

Best
