### ISSUE TITLE
There is a problem with the result of visual lung segmentation

### ISSUE THREAD

**Issue by kingjames1155** [rezazad68/BCDU-Net#39]
Dear author, thank you very much for opening up your code. 
I want to get the visualization results after lung segmentation. After I read the DCM file with simpleitk library, the results are shown in the figure below
![image](https://user-images.githubusercontent.com/71316665/169059550-22e398a3-2ef6-47ae-ba9d-93f52d179eb9.png)
Obviously, this result is wrong. 
`model = M.BCDU_net_D3(input_size = (512,512,1))` 
`model.load_weights('./weight/weight_lungD3.hdf5')` 
`vol = sitk.ReadImage('IM000090.dcm')` 
`volarray = sitk.GetArrayFromImage(vol)` 
`pre = model.predict(volarray)` 

This is the code I use. How do you visualize it, or what do you use as the input of the model?

**Comment by rezazad68** [comment]
Please follow our preprocessing and postprocessing steps to generate the segmentation map for your data.
