### ISSUE TITLE
There is no label under the test folder downloaded from DRIVE

### ISSUE THREAD

**Issue by Limingxing00** [rezazad68/BCDU-Net#4]
Hi! Thank you for publishing your code.  
When I run prepare_datasets_DRIVE.py in the DRIVE dataset, I found that the test does not contain  label, but your program requires the input variable "groundTruth_imgs_test". The test I downloaded contains only images and mask.

**Comment by rezazad68** [comment]
Hi,

Thanks for your interest. The original Drive dataset can be accessed through the following link:
https://www.isi.uu.nl/Research/Databases/DRIVE/download.php
But, It looks likes they newly forwarded this link to the ground challenge page, where they only provide the test images for the evaluation purpose. I have uploaded the full Drive data set to the google drive, so you can either download it from the google drive or from the main page that I mentioned above.

Google drive address for Drive dataset:
https://drive.google.com/open?id=17wVfELqgwbp4Q02GD247jJyjq6lwB0l6

Best

**Comment by Limingxing00** [comment]
Thank you very much! The issue will be closed.

Best
