### ISSUE TITLE
How ConvLSTM2D is learning the spatio-temporal information from individual image?

### ISSUE THREAD

**Issue by kiranshahi** [rezazad68/BCDU-Net#40]
As you have mentioned ConvLSTM2D is used for Spatio-temporal information. 
![image](https://user-images.githubusercontent.com/15968059/180089652-8c9869fd-3524-4521-93f3-d1cb3574b756.png)

But I am confused, is this model really going to learn the temporal information? There are two reasons for it.

- Your datasets are images and not videos.
- And you are using a Convolutional layer in your encoder and decoder but Bi-Directional ConvLSTM in skip connection.

![image](https://user-images.githubusercontent.com/15968059/180090268-bf2030da-73a2-48d1-a3f7-10de8e3cd93c.png)

Can you share your findings? Does this really work? 

Reference:
[Temporal Information](https://www.sciencedirect.com/topics/engineering/temporal-information)
[Stackoverflow answer](https://stackoverflow.com/a/56737485/5740382)

**Comment by rezazad68** [comment]
Thanks for your interest in our work. The objective of the Conv-LSTM here is not to learn spatial-temporal information. It acts as a mechanism to learn non-linear representation shared among decoding and encoding path. More specifically, we consider that the feature set coming from the encoder path contains more localization information while the decoder path brings semantic information, however, both tensors see the same object. To effectively map these two tensors into a combined version we use ConvLSTM.
