### ISSUE TITLE
Prerequisities

### ISSUE THREAD

**Issue by xihuanliuliu** [rezazad68/BCDU-Net#5]
Dear rezazad68 , can you tell the tensorflow and keras  version? Thanks.

**Comment by rezazad68** [comment]
Dear Xihuanliuliu,

Thanks for your comment. The Keras and Tensorflow version of my server are as follow:
Keras: version 2.2.0 and Tensorflow: 1.13.1

Also, some people already trained the model on Colab and other Keras/TensorFlow versions. Thus, the code should be compatible with other versions too. 

Best
