### ISSUE TITLE
Assertion Error 

### ISSUE THREAD

**Issue by MaleehaKhan** [rezazad68/BCDU-Net#6]
imgs max: 0.0
imgs min: 0.0
Traceback (most recent call last):
  File "prepare_datasets_DRIVE.py", line 82, in <module>
    imgs_train, groundTruth_train, border_masks_train = get_datasets(original_imgs_train,groundTruth_imgs_train,borderMasks_imgs_train,"train")
  File "prepare_datasets_DRIVE.py", line 67, in get_datasets
    assert(np.max(groundTruth)==255 and np.max(border_masks)==255)
AssertionError
kindly tell me how to resolve this? just tried to run prepare_datasets_DRIVE.py

**Comment by rezazad68** [comment]
Dear,
The assertion error shows that the data value is not in the original range 0-255 (which we use for drive data set), if you are using other data set or modified the code, try to use the original setting. 
to solve the above problem, check the max value of your groundTruth and border_masks data wherever they used in code, they should be 255 before normalization, if they are in range 0-1 then multiply them with 255 to pass the assertion error. 
Best

**Comment by MaleehaKhan** [comment]
Thanks for your reply
I am using Drive dataset, will try making some changes and will share if error gets resolved.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
