### ISSUE TITLE
About the prepare_data.py

### ISSUE THREAD

**Issue by lsoaringl** [rezazad68/BCDU-Net#7]
Can you tell me the meaning of Data_train, Mask_train, Maska_train，FOV_train obtained through Prepare_data.py?

**Comment by rezazad68** [comment]
Dear Isoaringl,

For Drive data set we have retina images (Data_train) with related segmentation (Mask_train) images (similar to any segmentation task). Also for each image we have some dark pixels around image boundaries which does not belongs to the image (we use FOV images to remove them). For example check the retinal image which I putted in the main page (https://github.com/rezazad68/BCDU-Net/blob/master/output_images/Figure_1.png), you can see the dark region around the image, those regions are not part of FOV and are not important for us, thus, we remove them using filed of view (FOV) information. 
In the Preparation code we extracts several patches from the 20 train images with overlapping. For more detail see the paper.

Best regards
