### ISSUE TITLE
Bi-Directional ConvLSTM?

### ISSUE THREAD

**Issue by YuhuiMa** [rezazad68/BCDU-Net#8]
In this code, is there still only one direction adopted by ConvLSTM?

**Comment by rezazad68** [comment]
Hello
you can use the following code to include bi-directional ConvLSTM:

LSTM_f = layers.ConvLSTM2D(filters = 128, kernel_size=(3, 3), padding='same', return_sequences = False,  go_backwards = False, kernel_initializer = 'he_normal')(X)    

LSTM_b = layers.ConvLSTM2D(filters = 128, kernel_size=(3, 3), padding='same', return_sequences = False,   go_backwards = True,  kernel_initializer = 'he_normal')(X)

Bi_rep = layers.Add()([LSTM_f, LSTM_b]) 

Good luck

**Comment by YuhuiMa** [comment]
I have got it. Many thanks!

2020-04-08 09:03:21"Reza Azad" <notifications@github.com>写道：

Hello
you can use the following code to include bi-directional ConvLSTM:

LSTM_f = layers.ConvLSTM2D(filters = 128, kernel_size=(3, 3), padding='same', return_sequences = False, go_backwards = False, kernel_initializer = 'he_normal')(X)

LSTM_b = layers.ConvLSTM2D(filters = 128, kernel_size=(3, 3), padding='same', return_sequences = False, go_backwards = True, kernel_initializer = 'he_normal')(X)

Bi_rep = layers.Add()([LSTM_f, LSTM_b])

Good luck

**Comment by mingyue333** [comment]
Thank you for your sharing, and i still confused about the differences between the two coding scheme of bi-directional ConvLSTM . One is what you discribed above ,the other is using the Bidirectional wrapper,like"BidirectionalConvLSTM2D(filters = 128, kernel_size=(3, 3), padding='same', kernel_initializer='he_normal', return_sequences=True)''.  Could you tell if  the second statement is correct, and if there are some differences between them
